# Generated by Django 3.0.7 on 2020-07-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0004_auto_20200708_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsent',
            name='name',
            field=models.CharField(default='No Name', max_length=200),
            preserve_default=False,
        ),
    ]
